### ISSUE TITLE
key storage definition using puppet-rundeck module

### ISSUE THREAD

**Issue by lgallardo-edrans** [voxpupuli/puppet-rundeck#287]
Is there a way to define keys in the key storage using this module?

I would like to include a key here:

/var/lib/rundeck/var/storage/meta/keys/
/var/lib/rundeck/var/storage/content/keys/

I know I can use a file resource, but I would like to know if is possibile using this module.

Regards,

**Comment by dalisch** [comment]
If you are using file-based keystores (as it seems you are) then yes, you can define your key properties as a hash like this:
https://github.com/voxpupuli/puppet-rundeck/blob/master/manifests/config/global/file_keystore.pp

...and pass them into the module via `$file_keystorage_keys`.

Note that the module (in its current design) only handles the use case for initial setup of the keys (i.e.: the file resources for the keys will not be updated/replaced if you manipulate them via the app).

HTH

**Comment by lgallardo-edrans** [comment]
Thanks, it works like a charm. I just need to create the key/password in order to use it with the SCM plugin. Here I leave my hieradata definition as example:


```
rundeck::file_keystorage_keys:
  mykey:
    value: 'secret'
    path: 'myproject/git'
    data_type: 'password'
    content_type: 'application/x-rundeck-data-password'
```

And for the SCM definition:

`      scm.import.config.gitPasswordPath: 'keys/myproject/git/mykey.password'`

Regards,
