### ISSUE TITLE
puppet adding double quotes to allow parameters

### ISSUE THREAD

**Issue by Arzyfex** [voxpupuli/puppet-rundeck#292]
I've been facing one issue while using this module. When I managing ACL rules from puppet like this,

`'job'  => [ {'equals' => { 'name' => 'myJob' }, 'allow' => ['run','read']}, ],`

this adds ACL rules in aclpolicy file as below,

```
description: 'Admin user access'
context:
  project: 'testproject'
for:
  job:
    - equals:
        name: 'myJob'
      allow: ["run", "read"]

```
see, there are extra double quotes in allow parameter, I suppose it should be

`allow => [run,read]` but not `allow => ["run","read"]`.

Because of this extra double quotes, user which I am managing from puppet can't see job assigned to it. I tested out ACL file without double quotes it works fine, but not when it has double quotes to run and read.

Kindly help me on this.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.7
- Ruby: 2.1
- Distribution: Debian Jessie 8.6
- Module version: 3.0.0
