### ISSUE TITLE
ACLs render incorrectly when using attributes filters

### ISSUE THREAD

**Issue by nosrio** [voxpupuli/puppet-rundeck#512]
When creating an acl to filter using nodes attributes the acl file is rendered incorrectly

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7
- Ruby:
- Distribution:
- Module version: 8

## How to reproduce (e.g Puppet code you use)

Using this ACL
```
rundeck::config::aclpolicyfile { 'read-qa-nodes':
  acl_policies => [
     {
        'description' => 'Read qa nodes',
        'context' => {
          'project' => '.*'
        },
        'for' => {
          'node' => [
            { 'match' => { 'environment' => 'qa' }, 'allow' => ['read'] }
          ]
        },
        'by' => [
          { 'group' => ['qa'] }
        ]
      }
  ]
}
```

## What are you seeing

The ACL rendered is this:

```
description: 'Read qa nodes'
context:
  project: '.*'
for:
  node:
    - match:
      environment: 'qa'    ### <-- THIS IS INCORRECT
      allow: ["read"]
by:
  group:
    - 'qa'
```
## What behaviour did you expect instead

The ACL should be this (with the extra indent)

```
description: 'Read qa nodes'
context:
  project: '.*'
for:
  node:
    - match:
        environment: 'qa'
      allow: ["read"]
by:
  group:
    - 'qa'
```
